### ISSUE TITLE
(Help requested) First time building AOSP and LineageOS-based ROM

### ISSUE THREAD

**Issue by gittoasted** [begonia-dev/android_device_redmi_begonia#4]
Hello, 
I recently started a personal test build of DivestOS (LineageOS fork) based on the begonia phone. From my rough understanding of the base build of LineageOS and aosp in general I created the following environment:

```
        <!-- Xiaomi Redmi Note 8 Pro (begonia) -->
        <project path="hardware/xiaomi" name="LineageOS/android_hardware_xiaomi" remote="github" revision="lineage-20" />
        <project path="device/xiaomi/begonia" name="begonia-dev/android_device_redmi_begonia" remote="github" revision="13.0" />
        <project path="kernel/xiaomi/mt6785" name="begonia-dev/android_kernel_xiaomi_mt6785" remote="github" revision="13.0" />
        <project path="vendor/xiaomi/mt6785-common" name="begonia-dev/android_hardware_mediatek" remote="github" revision="13.0" />
        <project path="vendor/xiaomi/begonia-ims" name="begonia-dev/android_vendor_redmi_begonia-ims" remote="github" revision="13.0" />

```
I have a feeling my directories aren't properly put and might lack something. When excecuting "breakfast lineage_begonia-user" I end up with an error that device.mk is not found which is weird since it is in the "android_device_redmi_begonia" repo. 

My questions are:
How can I improve or fix the directories of my build environment (without using scripts at first)?
Is any of the repos in begonia-dev absolutely necessary in order to build lineageos-20?
Any ideas on why the device.mk file seems to not be found? (it perhaps has to do with a script somewhere, if so I'll try to copy it in a further reply)

Thank you for your time

**Comment by DarkJoker360** [comment]
almost all device related repos are necessary to build a fully working rom for begonia

**Comment by gittoasted** [comment]
> almost all device related repos are necessary to build a fully working rom for begonia

Thank you very much for your answer. After some time researching documents and help regarding the begonia device, I think it might be easier to pick a straight LineagesOS 20.0 and build from there. Is the version on your sourceforge repo usable in any way?
Again, thank you, and have a good one.
